apiVersion: v1
kind: PersistentVolume
metadata:
  name: ms-restaurant-db-persistent-volume
  labels:
    type: local
    app: ms-restaurant-db
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: '/Users/tombrulin/Documents/CESI/GoodFood/volumes/ms-restaurant/db'
