apiVersion: v1
kind: Secret
metadata:
  name: ms-restaurant-secret
type: Opaque
data:
  APP_KEY: bS0wX1psMWF4aDIwOXFkaU1GYThiTTdzNVlvdU9DbUY=
  GEOAPIFY_TOKEN: NzU3YmRiYmMzMGI0NDVkOTlmN2JlYjlhZjdmMjJhMTI=
